name: Python package build on Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Update package list
      run: |
        sudo apt-get update

    - name: Install git
      run: |
        sudo apt-get install -y git

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo apt-get install -y python3 python3-pip libhdf5-dev limesuite python3-setuptools automake gcc pkg-config build-essential python3-build

    - name: Build the package
      run: |
        python -m build
