name: Python package build on Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Update package list
      run: |
        sudo apt-get update

    - name: Install git
      run: |
        sudo apt-get install -y git

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Prepare Python environment
      run: |
        pip install --upgrade pip h5py setuptools wheel build

    - name: Install dependencies
      run: |
        sudo apt-get install -y libhdf5-dev limesuite liblimesuite-dev automake gcc pkg-config build-essential python-is-python3

    - name: Install the package
      run: |
        pip install .

    - name: Test if the package can be imported
      run: |
        python -m limedriver